version: '3'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        image: nginx:1.17.9-alpine
        depends_on:
            - mysql
            - php
        ports:
            - '80:80'
        volumes:
            - './src:/var/www/html'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'

        networks:
            - laravel
    
    mysql:
        container_name: mysql
        image: mysql:8.0.19
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        volumes:
            - './mysql:/var/lib/mysql'

        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - './src:/var/www/html'
        ports:
            - '9000:9000'

        networks:
            - laravel
    
    composer:
        container_name: composer
        image: composer:1.10.0
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
    npm:
        container_name: npm
        image: node:12.16.1
        volumes:
            - './src:/var/www/html'
        working_dir: '/var/www/html'
        entrypoint: ['npm']
        networks:
            - laravel
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks:
            - laravel
