version: '3'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        image: nginx:1.17.9-alpine
        depends_on:
            - mysql
            - php
        ports:
            - '80:80'
        volumes:
            - './src:/var/www/html'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'

        networks:
            - laravel
    
    mysql:
        container_name: mysql
        image: mysql:8.0.19
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        volumes:
            - './mysql:/var/lib/mysql'

        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - './src:/var/www/html'
        ports:
            - '9000:9000'

        networks:
            - laravel